sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - realpath

install:
  - docker pull ubuntu:bionic

script:
 - docker run --rm -v $(pwd)/:/build/ -w /build/ ubuntu:bionic /bin/bash travis-build.sh

notifications:
  email: false
